<a href="https://colab.research.google.com/github/JosePabloGFnl/Tensorflow-Practice/blob/main/Module2IntroductionToTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x #always start with this when you want to use tensorflow
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
#creating tensors

#rank 0 tensors
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

#ranks/degrees of tensors
rank1_tensor = tf.Variable(["Test","Hello","Pablo"], tf.string) #one list, one array, one dimension
rank2_tensor = tf.Variable([["Test","Hello"],["Test","Rank 2"]], tf.string)

In [ ]:
#to determine the rank of a tensor
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
#Shape of tensors
rank1_tensor.shape

TensorShape([3])

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

In [ ]:
#changing shapes
tensor1 = tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) #-1 tells the tensor to calculare the size of the dimension in that place
                                       # this will reshape the tensor to [3,2]
#the number of elements in the reshape tensor must match the number in the original

In [ ]:
print("Tensor 1:")
print(tensor1)
print("Tensor 2:")
print(tensor2)
print("Tensor 3:")
print(tensor3)

Tensor 1:
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
Tensor 2:
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
Tensor 3:
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
#Types of tensors
with tf.Session() as sess: #creates a session using the default graph
  tensor.eval() #tensor will of course be the name of your tensor

AttributeError: ignored

In [ ]:
t = tf.zeros([5,5,5,5,5])
print(t)

tf.Tensor(
[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
   

In [ ]:
t = tf.reshape(t,[125, -1])
print(t)

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(125, 25), dtype=float32)
